######################## default configuration ####################
baseURL = "https://healthcomplex.dk/"
title = "Copenhagen Health Complexity Center"
theme = "educenter-hugo"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Europe/Copenhagen"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
# googleAnalytics = "UA-123456-78" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disable language
# disableLanguages = ["Dk"] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 75
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo_green.png"
# Meta data
description = "Official website of the Copenhagen Health Complexity Center"
author = "University of Copenhagen"
# contact info
address = "Bartholinsgade 2, DK-1356 Copenhagen K"
mobile = ""
email = "complex@sund.ku.dk"
# contact form action
#contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
#google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.png" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "55.686564795532824"
map_longitude = "12.56837689304564"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 2
  
############################# social site ########################
#[[params.social]]
#title = "facebook"
#icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "twitter"
#icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "github"
#icon = "ti-github" # themify icon : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#title = "linkedin"
#icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
#link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[Languages.en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2024 based on the [Educenter Hugo theme](https://github.com/themefisher/educenter-hugo)"


################### English navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Research"
url = "research/"
weight = 1

  [[Languages.en.menu.main]]
  parent = "Research"
  name = "Research themes"
  url = "research/"

  [[Languages.en.menu.main]]
  parent = "Research"
  name = "Publications"
  url = "publications/"

  [[Languages.en.menu.main]]
  parent = "Research"
  name = "Public engagement"
  url = "engagement/"

[[Languages.en.menu.main]]
name = "Education"
url = "education/"
weight = 2

  [[Languages.en.menu.main]]
  parent = "Education"
  name = "Courses"
  url = "courses/"

  [[Languages.en.menu.main]]
  parent = "Education"
  name = "Student Projects"
  url = "studentprojects/"


[[Languages.en.menu.main]]
weight = 3
name = "Community"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Community"
  name = "People"
  url = "people/"

  [[Languages.en.menu.main]]
  parent = "Community"
  name = "Advisory group"
  url = "advisory/"

  [[Languages.en.menu.main]]
  parent = "Community"
  name = "Fellows"
  url = "fellows/"

[[Languages.en.menu.main]]
weight = 4
name = "About us"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "Mission"
  url = "mission/"

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "Values"
  url = "values/"

  [[Languages.en.menu.main]]
  parent = "About us"
  name = "Contact"
  url = "contact/"


# footer menu

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.en.menu.footer]]
name = "event"
url = "event/"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.en.menu.footer]]
name = "research"
url = "research/"



################################### Danish language #####################################
#[Languages.dk]
#languageName = "Dk"
#languageCode = "dk-dk"
#contentDir = "content/danish"
#weight = 2

[Languages.dk.params]
home = "Hjemmeside"
# copyright
copyright = "Copyright &copy; 2024 based on the [Educenter Hugo theme](https://github.com/themefisher/educenter-hugo)"



################### Danish navigation ####################

# main menu
[[Languages.dk.menu.main]]
name = "À propos"
url = "about/"
weight = 1

[[Languages.dk.menu.main]]
name = "Cours"
url = "course/"
weight = 2

[[Languages.dk.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.dk.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.dk.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.dk.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event/"

  [[Languages.dk.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship/"

  [[Languages.dk.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
[[Languages.dk.menu.main]]
name = "blog"
url = "blog/"
weight = 4
  
[[Languages.dk.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.dk.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.dk.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.dk.menu.footer]]
name = "event"
url = "event/"

[[Languages.dk.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.dk.menu.footer]]
name = "research"
url = "research/"
