[build]
publish = "public"
command = "hugo --gc --minify --templateMetrics --templateMetricsHints --buildDrafts --buildExpired --buildFuture --forceSyncStatic"

[build.environment]
HUGO_VERSION = "0.128.2"
GO_VERSION = "1.20.5"
HUGO_BASEURL = "/"